version: "3.9"

services:
  dev-db:
    image: postgres
    env_file: .env
    ports:
      - "5434:5432"
    networks:
      - db-postgres

  app:
    build : .
    image: app
    env_file: .env
    ports:
      - "3000:3000"
    networks:
      - db-postgres
    depends_on:
      - dev-db

networks:
  db-postgres:
